//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchServer.SearchServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchServiceReference.ISearchServiceMain")]
    public interface ISearchServiceMain {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchServiceMain/GetData", ReplyAction="http://tempuri.org/ISearchServiceMain/GetDataResponse")]
        string GetData(string Prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchServiceMain/GetData", ReplyAction="http://tempuri.org/ISearchServiceMain/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string Prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchServiceMain/SetPath", ReplyAction="http://tempuri.org/ISearchServiceMain/SetPathResponse")]
        void SetPath(string Path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchServiceMain/SetPath", ReplyAction="http://tempuri.org/ISearchServiceMain/SetPathResponse")]
        System.Threading.Tasks.Task SetPathAsync(string Path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchServiceMainChannel : SearchServer.SearchServiceReference.ISearchServiceMain, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceMainClient : System.ServiceModel.ClientBase<SearchServer.SearchServiceReference.ISearchServiceMain>, SearchServer.SearchServiceReference.ISearchServiceMain {
        
        public SearchServiceMainClient() {
        }
        
        public SearchServiceMainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceMainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceMainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceMainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string Prefix) {
            return base.Channel.GetData(Prefix);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string Prefix) {
            return base.Channel.GetDataAsync(Prefix);
        }
        
        public void SetPath(string Path) {
            base.Channel.SetPath(Path);
        }
        
        public System.Threading.Tasks.Task SetPathAsync(string Path) {
            return base.Channel.SetPathAsync(Path);
        }
    }
}
